# Generated by Django 3.1.1 on 2020-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='Post.Tag'),
        ),
    ]
