# Generated by Django 3.1.1 on 2020-09-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200920_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
