# Generated by Django 3.1.1 on 2020-09-21 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0007_post_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(related_name='save', to=settings.AUTH_USER_MODEL),
        ),
    ]
