# Generated by Django 3.1.1 on 2020-09-21 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0008_post_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='Post.Tag'),
        ),
    ]
