# Generated by Django 3.1.1 on 2020-09-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
